# Generated by Django 5.2.12 on 2026-05-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='packing_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='specifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
