# Generated by Django 5.2.12 on 2026-05-12 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_alter_blog_subtitle_alter_blog_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='custom_admin.productcategory'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='real_subcategories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_subcategories', to='custom_admin.productcategory')),
            ],
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='custom_admin.subcategory'),
        ),
    ]
