# Generated by Django 5.2.12 on 2026-05-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_contactenquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='interested_product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
