# Generated by Django 5.2.12 on 2026-05-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0005_alter_contactenquiry_interested_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='pending', max_length=50, null=True),
        ),
    ]
