# Generated by Django 5.2.12 on 2026-07-24 05:19

import custom_admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0006_contactenquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='category_video',
            field=models.FileField(blank=True, null=True, upload_to='categories/videos/', validators=[custom_admin.models.validate_video_file]),
        ),
    ]
