# Generated by Django 5.2.12 on 2026-07-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0007_productcategory_category_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('product_category', models.CharField(max_length=255)),
                ('manufacturing_capacity', models.TextField()),
                ('export_experience', models.CharField(max_length=100)),
                ('certifications', models.TextField()),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('company_profile', models.FileField(blank=True, null=True, upload_to='supplier_profiles/')),
                ('certifications_file', models.FileField(blank=True, null=True, upload_to='supplier_certs/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
