# Generated by Django 5.2.12 on 2026-07-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0008_supplierregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierregistration',
            name='minimum_order_quantity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplierregistration',
            name='monthly_supply_capacity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplierregistration',
            name='products_you_supply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
